name: 1_Create PR from selected branch to main

on:
  workflow_dispatch:

jobs:
  create-pull-request-release2main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ github.ref_name }}
        destination_branch: main
        pr_title: "Merge ${{ github.ref_name }} into main"
        pr_body: "This PR was automatically created by GitHub Actions."
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
  create-pull-request-main2develop:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: main
        destination_branch: develop
        pr_title: "Merge main into develop"
        pr_body: "This PR was automatically created by GitHub Actions."
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
