name: Tag Latest Commit

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to tag'
        required: true
        type: string
      tag_name:
        description: 'Name of the tag'
        required: true
        type: string

jobs:
  tag_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create tag
        run: |
          git fetch --tags
          git tag -a ${{ github.event.inputs.tag_name }} -m "Tagging commit ${{ github.sha }}"
          git push origin ${{ github.event.inputs.tag_name }}
