name: Tag Main on Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract source branch name
      id: extract_branch
      run: echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

    - name: Create Tag
      run: |
        TAG_NAME="${{ env.BRANCH_NAME }}"
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
