name: Tag Latest Commit

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name of the tag'
        required: true
        type: string

jobs:
  tag_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag
        run: |
          # Get the branch name from the GitHub context
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')

          # Fetch the latest commits and create a tag
          git fetch --tags
          git tag -a ${{ github.event.inputs.tag_name }} -m "Tagging commit on branch $BRANCH_NAME"
          git push origin ${{ github.event.inputs.tag_name }}
